### PR TITLE
Improve identifier handling

### PR DESCRIPTION
**Pull request by ardecvz**
Hello again!

I've touched the current identifier handling to fix some small user-burden issues.

Please see `item_spec.rb` to grasp the proposed changes easily.

Thanks!

### CODE REVIEW

**Comment by k0kubun** [comment]
Thank you for your contribution.

I guess you want to specify the same name for several items. But why do you want to do that? As far as I know, you can add some remap configurations to one item. I couldn't understand the real use-case from item_spec.rb. Could you show your configuration?

**Comment by ardecvz** [comment]
It's for a marginal use case such as:
```
item 'TEMPORARY' do
  remap 'VOLUME_UP', to: nil
end
# Quick copy-paste and small change in the name of science
item 'TEMPORARY' do
  remap 'VOLUME_DOWN', to: nil
end
```
And I need to switch on/off the second rule independently from the first one.

So it's basically to hide xml internals with identifiers and duplicate errors completely from users. Nice to have but not super important - you could cherry-pick or ask for rebase.

**Comment by k0kubun** [comment]
OK. I accept your proposal. But your implementation is a little complex. Can it be achieved by postfixing global incremental index or securely random string?

**Comment by ardecvz** [comment]
Hmmm... Yeah, you're right, it could be more KISSed ;) 
I'll rebase with global incremental index (imho, random strings don't fit in as they would change every run and turn their included settings off in the Karabiner's panel).
However, I resist to remove new XmlTree methods right now as they could be useful in implementing [the roadmap](https://github.com/k0kubun/karabiner-dsl/issues/9).

**Comment by k0kubun** [comment]
> (imho, random strings don't fit in as they would change every run and turn their included settings off in the Karabiner's panel).

Ah, you're right. :)

**Comment by ardecvz** [comment]
Cherry-picked by 5508c5f and 26eedf8.

P.S.: a new [Karabiner-Elements for Sierra ](https://github.com/tekezo/Karabiner-Elements) seems to support only JSON for configurations. We should add a new output format and, maybe, XML->Karabiner DSL->JSON converter to help people (so we probably need the proper XML gem like [Oga](https://github.com/YorickPeterse/oga) in order to not reinvent the wheel).

**Pull request closed without merging**
